### PR TITLE
slack send should not require message

### LINKED ISSUE #351: Missing required parameter: "message"
I followed the instructions on the README to send a slack notification from a declarative pipeline as such:

```
slackSend(channel: '#bots', attachments: getSlack(currentBuild).toString())
```
However, I got the following error from Jenkins
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 136: Missing required parameter: "message" @ line 136, column 4.
```

I am using version 2.3

### PR DESCRIPTION
**Pull request by casz**
fixes #351

### CODE REVIEW

**Comment by timja** [comment]
Thanks @casz will get this into 2.5

**Comment by timja** [comment]
Tests failing @casz will get into next release

File: src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java [hunk 1]
```diff
@@ -144,11 +144,14 @@ public String getAttachments(){
...
 
-    @DataBoundConstructor
-    public SlackSendStep(@Nonnull String message) {
+    @DataBoundSetter
+    public void setMessage(String message) {
         this.message = message;
     }
 
+    @DataBoundConstructor
+    public SlackSendStep() { }
```
Comment (casz) [inline src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java]: We could keep the old ctor but I doubt anyone is calling the constructor except for this plugin.

Comment (timja) [reply src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java]: happy to remove

Comment (timja) [reply src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java]: do you need this constructor?

Comment (casz) [reply src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java]: We need to keep a `@DataBoundConstructor` otherwise stapler is not happy 😅
I was thinking the old ctor with `SlackSendStep(String message)`

**Comment by casz** [comment]
Tests runs fine locally, Jenkins CI is just having a field day 😅

**Comment by timja** [comment]
good to go once jenkins plays ball 👍

**Comment by timja** [comment]
failed :(

**Comment by casz** [comment]
@timja Test passed 😅

**Comment by timja** [comment]
will release later today
