### PR TITLE
Fix concurrent build back to normal notification missed

### LINKED ISSUE #544: Back to normal notifications missed
For our builds we allow more that one build of the same type to run at the same time. If a build has failed, then two further builds run (started at different times) then then "back to normal" message is not sent.

The following slack notifications are set:
- Notify Unstable
- Notify First Failure Only
- Notify Repeated Failure Only
- Notify Back To Normal

So the sequence is:
1. Build 1 run and fails
2. Build 2 runs
3. While build 2 is running build 3 starts
4. Build 2 completes and fixes the build - **this doesn't trigger the "back to normal"**
5. Build 3 completes - no message sent (as expected).

In the log I see a message like this - note this comes from build **# 91**.
[Slack Notifications] found **# 91** as previous completed, non-aborted build

Is there any way around this?

### PR DESCRIPTION
**Pull request by EricBartusch**
Fixes #544 

Added a check to make sure that the same builds aren't being compared with each other.  

It seems like when two concurrent builds are happening, the context for the `project` variable gets changed so the `project.getLastBuild()` ends up returning the newest build even though `r` is still the earlier of the two.  This makes `r` and `previousBuild` refer to the same build and break the `OnBackToNormal` check.

### CODE REVIEW

File: src/main/java/jenkins/plugins/slack/ActiveNotifier.java [hunk 1]
```diff
@@ -134,7 +134,7 @@ public void completed(AbstractBuild r) {
         if (null != previousBuild) {
             do {
                 previousBuild = previousBuild.getPreviousCompletedBuild();
-            } while (null != previousBuild && previousBuild.getResult() == Result.ABORTED);
+            } while ((null != previousBuild && previousBuild.getResult() == Result.ABORTED) || previousBuild.getNumber() == r.getNumber());
```
Comment (timja) [inline src/main/java/jenkins/plugins/slack/ActiveNotifier.java]: seems ok, have you tested it out?

Comment (EricBartusch) [reply src/main/java/jenkins/plugins/slack/ActiveNotifier.java]: Yep, I was able to reproduce the error on the local Jenkins instance created by running the plugin.  I confirmed that when I made my change the notification properly showed up as well as logging the last build properly, fixing #568 too.

I'll check out the failing build and push more changes if need be.
